apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: uat
resources:
  - ../../../base/auth-service
  - external-secret.yaml
  - canary-service.yaml
images:
  - name: detailsnap/auth-service
    newName: 651084712750.dkr.ecr.us-east-1.amazonaws.com/detailsnap/auth-service
    newTag: uat-v1.0.0-rc.1
patches:
  - patch: |-
      - op: add
        path: /spec/template/spec/nodeSelector
        value:
          env: uat
      - op: replace
        path: /spec/template/spec/containers/0/env/0
        value:
          name: DB_NAME
          value: detailsnap_uat
      - op: replace
        path: /spec/template/spec/containers/0/env/1
        value:
          name: CORS_ORIGIN
          value: https://uat.tlecuyer.codes
      - op: replace
        path: /spec/replicas
        value: 4
      - op: replace
        path: /spec/strategy
        value:
          canary:
            canaryService: auth-service-canary
            stableService: auth-service
            steps:
              - setWeight: 25
              - pause: {}
              - setWeight: 50
              - pause: {}
              - setWeight: 75
              - pause: {}
              - setWeight: 100
              - pause: {}
    target:
      kind: Rollout
      name: auth-service
