apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mysql-exporter-credentials
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: mysql-exporter-credentials
    creationPolicy: Owner
  data:
    - secretKey: DATA_SOURCE_NAME
      remoteRef:
        key: detailsnap/mysql-exporter
        property: dsn
