- op: replace
  path: /metadata/annotations/alb.ingress.kubernetes.io~1certificate-arn
  value: arn:aws:acm:us-east-1:651084712750:certificate/041c345d-959a-4e4f-92ce-beef2752828d
- op: replace
  path: /metadata/annotations/external-dns.alpha.kubernetes.io~1hostname
  value: tlecuyer.codes
