apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod
resources:
  - ../../../base/gateway
patches:
  - patch: |-
      - op: replace
        path: /spec/hostnames/0
        value: prod.tlecuyer.codes
    target:
      kind: HTTPRoute
      name: main
