apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: app-credentials
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: app-credentials
    creationPolicy: Owner
  data:
    - secretKey: DB_HOST
      remoteRef:
        key: detailsnap/db
        property: host
    - secretKey: DB_PORT
      remoteRef:
        key: detailsnap/db
        property: port
    - secretKey: DB_USER
      remoteRef:
        key: detailsnap/db
        property: username
    - secretKey: DB_PASSWORD
      remoteRef:
        key: detailsnap/db
        property: password
    - secretKey: JWT_SECRET
      remoteRef:
        key: detailsnap/jwt
        property: secret
