apiVersion: batch/v1
kind: Job
metadata:
  name: flyway-migrate
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-wave: "0"
spec:
  backoffLimit: 2
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: flyway
          image: detailsnap/migrations
          args:
            - migrate
            - -url=jdbc:mysql://$(DB_HOST):$(DB_PORT)/$(DB_NAME)?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: app-credentials
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: app-credentials
                  key: DB_PORT
            - name: FLYWAY_USER
              valueFrom:
                secretKeyRef:
                  name: app-credentials
                  key: DB_USER
            - name: FLYWAY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-credentials
                  key: DB_PASSWORD
            - name: DB_NAME
              value: detailsnap
