apiVersion: v1
kind: Service
metadata:
  name: auth-service
  annotations:
    alb.ingress.kubernetes.io/target-type: ip
spec:
  selector:
    app: auth-service
  ports:
    - port: 8081
      targetPort: 8081
