- op: replace
  path: /metadata/annotations/alb.ingress.kubernetes.io~1certificate-arn
  value: arn:aws:acm:us-east-1:651084712750:certificate/990f6b7f-dd98-4771-bc78-47ee311f94d6
- op: replace
  path: /metadata/annotations/external-dns.alpha.kubernetes.io~1hostname
  value: uat.tlecuyer.codes
