- op: replace
  path: /metadata/annotations/alb.ingress.kubernetes.io~1certificate-arn
  value: arn:aws:acm:us-east-1:651084712750:certificate/073213ad-dfd7-4a51-8d21-3d5601b250d5
- op: replace
  path: /metadata/annotations/external-dns.alpha.kubernetes.io~1hostname
  value: uat.tlecuyer.codes
