apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: uat
resources:
  - ../../../base/core-service
  - external-secret.yaml
images:
  - name: detailsnap/core-service
    newName: 651084712750.dkr.ecr.us-east-1.amazonaws.com/detailsnap/core-service
    newTag: latest
patches:
  - patch: |-
      - op: add
        path: /spec/template/spec/nodeSelector
        value:
          env: uat
      - op: replace
        path: /spec/template/spec/containers/0/env/1
        value:
          name: CORS_ORIGIN
          value: https://uat.tlecuyer.codes
    target:
      kind: Deployment
      name: core-service
