apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cluster-secret-store.yaml
  - applicationset.yaml
  - ecr-token-refresh.yaml
  - monitoring-infra-app.yaml
  - monitoring-stack-app.yaml
  - loki-app.yaml
  - alloy-app.yaml
  - argo-rollouts-gateway-plugin.yaml
