apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: uat
resources:
  - ../../../base/migrations
images:
  - name: detailsnap/migrations
    newName: 651084712750.dkr.ecr.us-east-1.amazonaws.com/detailsnap/migrations
    newTag: v1.0.1-rc.1
  - name: 651084712750.dkr.ecr.us-east-1.amazonaws.com/detailsnap/migrations
    newTag: v1.1.0-rc.2
patches:
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/4/value
        value: detailsnap_uat
    target:
      kind: Job
      name: flyway-migrate
