apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: uat
resources:
  - ../../../base/migrations
patches:
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/4/value
        value: detailsnap_uat
    target:
      kind: Job
      name: flyway-migrate
