apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod
resources:
  - ../../../base/auth-service
  - preview-service.yaml
images:
  - name: detailsnap/auth-service
    newName: 651084712750.dkr.ecr.us-east-1.amazonaws.com/detailsnap/auth-service
    newTag: v1.0.0
patches:
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 4
      - op: add
        path: /spec/template/spec/nodeSelector
        value:
          env: prod
      - op: replace
        path: /spec/template/spec/containers/0/env/0
        value:
          name: DB_NAME
          value: detailsnap_prod
      - op: replace
        path: /spec/template/spec/containers/0/env/1
        value:
          name: CORS_ORIGIN
          value: https://prod.tlecuyer.codes
      - op: replace
        path: /spec/strategy
        value:
          blueGreen:
            activeService: auth-service
            previewService: auth-service-preview
            autoPromotionEnabled: false
            scaleDownDelaySeconds: 30
    target:
      kind: Rollout
      name: auth-service
