apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: uat
resources:
  - ../../../base/frontend
  - canary-service.yaml
images:
  - name: detailsnap/frontend
    newName: 651084712750.dkr.ecr.us-east-1.amazonaws.com/detailsnap/frontend
    newTag: latest
patches:
  - patch: |-
      - op: add
        path: /spec/template/spec/nodeSelector
        value:
          env: uat
      - op: replace
        path: /spec/replicas
        value: 4
      - op: replace
        path: /spec/strategy
        value:
          canary:
            canaryService: frontend-canary
            stableService: frontend
            steps:
              - setWeight: 25
              - pause: {}
              - setWeight: 50
              - pause: {}
              - setWeight: 75
              - pause: {}
              - setWeight: 100
              - pause: {}
    target:
      kind: Rollout
      name: frontend
